services:
  pocketbase:
    build:
      context: . # Use the current directory as the build context
      dockerfile: Dockerfile # Specify the Dockerfile name if different
    ports:
      - "8080:8080"
    volumes:
      - ./pb_data:/pb/data
