# fly.toml app configuration file generated for tots-challenge on 2024-11-06T11:33:55-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tots-challenge'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
  [http_service.concurrency]
    type = "requests"
    soft_limit = 500
    hard_limit = 550

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  destination = "/pb/pb_data"
  source = "pb_data"
 
